name: Deploy Python Application

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install AWS CLI
      id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2 
    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1 
          
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12.2
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.0-alpha - 3.12.0'

    - name: Install dependencies
      run: |
        python3.12 -m venv venv
        source venv/bin/activate
        pip3.12 install -r requirements.txt
    - name: Run server
      run: |
        source venv/bin/activate
        nohup uvicorn app.main:app --host localhost --port 8000 --reload > uvicorn.log 2>&1 &
        sleep 2
    - name: Run tests
      run: |
        source venv/bin/activate
        pytest
    - name: Find and stop Uvicorn process
      run: |
        PID=$(ps aux | grep 'uvicorn app.main:app' | grep -v grep | awk '{print $2}'); [ -n "$PID" ] && kill $PID && echo "Stopped uvicorn process with PID $PID" || echo "No uvicorn process found"
    - name: cleanup
      run: |
        sudo rm -rf venv
    - name: Create Deploy Bundle
      run: |
        zip -r app.zip .
        aws s3 cp app.zip s3://python-codedeploy/python/

    - name: Deploy to CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name python \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name python-stage \
          --s3-location bucket=python-codedeploy,key=python/app.zip,bundleType=zip \
          --description "Deployment from GitHub Actions"